name: test.yaml

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Cache Go Migrate CLI
        id: cache-migrate
        uses: actions/cache@v5
        with:
          path: /usr/local/bin/migrate
          key: ${{ runner.os }}-migrate-v4.19.1

      - name: Install Go Migrate CLI
        if: steps.cache-migrate.outputs.cache-hit != 'true'
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: SQL Migrations
        run: |
          migrate -path authentication/migrations -database "postgres://test:test@localhost:5432/test?sslmode=disable" up
          migrate -path portfolio/migrations -database "postgres://test:test@localhost:5432/test?sslmode=disable" up

      - name: Setup SQLc CLI
        uses: sqlc-dev/setup-sqlc@v5
        with:
          sqlc-version: '1.31.1'

      - name: Run SQLc Generate
        run: sqlc generate
