name: test.yaml

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true

      - name: Setup SQLc CLI
        uses: sqlc-dev/setup-sqlc@v5
        with:
          sqlc-version: '1.31.1'

      - name: Run SQLc Generate
        run: sqlc generate

      - name: Run tests
        run: go test -v ./...
